#!/usr/bin/env python3
"""Generate C guard tests for the public Metal backend entry points."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Sequence


@dataclass(frozen=True)
class MetalCase:
    name: str
    args: Sequence[str]
    invalid_arg: int
    unsupported_arg: int
    unsupported_value: str = "bad_type"


CASES: tuple[MetalCase, ...] = (
    MetalCase("te_metal_matvec_f32", ("mapping", "mapping_len", "0u", "q4_type", "f32", "4u", "4u", "f32"), 0, 3),
    MetalCase("te_metal_matvec_argmax_f32", ("mapping", "mapping_len", "0u", "q4_type", "f32", "4u", "4u", "&index"), 0, 3),
    MetalCase("te_metal_project_argmax_f32", ("mapping", "mapping_len", "0u", "q8_type", "f32", "f32", "4u", "4u", "1e-6f", "&index"), 0, 3),
    MetalCase("te_metal_matvec2_f32", ("mapping", "mapping_len", "0u", "0u", "q4_type", "f32", "4u", "4u", "f32", "f32_alt"), 0, 4),
    MetalCase("te_metal_matvec_batch_f32", ("mapping", "mapping_len", "0u", "q4_type", "f32", "1u", "4u", "4u", "f32"), 0, 3),
    MetalCase("te_metal_qkv_f32", ("mapping", "mapping_len", "0u", "0u", "0u", "q4_type", "f32", "4u", "4u", "f32", "f32_alt", "f32_third"), 0, 5),
    MetalCase("te_metal_qkv_batch_f32", ("mapping", "mapping_len", "0u", "0u", "0u", "q4_type", "f32", "1u", "4u", "4u", "f32", "f32_alt", "f32_third"), 0, 5),
    MetalCase("te_metal_mlp_f32", ("mapping", "mapping_len", "0u", "0u", "0u", "q4_type", "f32", "4u", "4u", "f32"), 0, 5),
    MetalCase("te_metal_mlp_batch_f32", ("mapping", "mapping_len", "0u", "0u", "0u", "q4_type", "f32", "1u", "4u", "4u", "f32"), 0, 5),
    MetalCase("te_metal_post_attn_mlp_f32", ("mapping", "mapping_len", "0u", "0u", "0u", "0u", "q4_type", "f32", "f32_alt", "f32_third", "4u", "4u", "1e-6f", "f32"), 0, 6),
    MetalCase("te_metal_post_attn_mlp_batch_f32", ("mapping", "mapping_len", "0u", "0u", "0u", "0u", "q4_type", "f32", "f32_alt", "f32_third", "1u", "4u", "4u", "1e-6f", "f32"), 0, 6),
    MetalCase("te_metal_decode_layer_f32", ("mapping", "mapping_len", "0u", "0u", "0u", "0u", "0u", "0u", "0u", "q4_type", "f32", "f32_alt", "f32_third", "f32", "f32_alt", "f32_third", "f32", "f32_alt", "f32", "f32_alt", "0u", "1u", "4u", "4u", "1u", "1u", "4u", "4u", "1e-6f", "f32"), 0, 9),
    MetalCase("te_metal_decode_all_layers_f32", ("mapping", "mapping_len", "offsets", "offsets", "offsets", "offsets", "offsets", "offsets", "offsets", "1u", "q4_type", "f32", "f32_alt", "f32_third", "f32", "f32_alt", "f32_third", "f32", "f32_alt", "f32", "f32_alt", "0u", "1u", "4u", "4u", "1u", "1u", "4u", "4u", "1e-6f", "f32", "0u", "q8_type", "f32", "4u", "&index"), 0, 10),
    MetalCase("te_metal_prefill_layer_f32", ("mapping", "mapping_len", "0u", "0u", "0u", "0u", "0u", "0u", "0u", "q4_type", "f32", "f32_alt", "f32_third", "f32", "f32_alt", "f32_third", "f32", "f32_alt", "f32", "f32_alt", "1u", "1u", "4u", "4u", "1u", "1u", "4u", "4u", "1e-6f", "f32"), 0, 9),
    MetalCase("te_metal_prefill_all_layers_f32", ("mapping", "mapping_len", "offsets", "offsets", "offsets", "offsets", "offsets", "offsets", "offsets", "1u", "q4_type", "f32", "f32_alt", "f32_third", "f32", "f32_alt", "f32_third", "f32", "f32_alt", "f32", "f32_alt", "1u", "1u", "4u", "4u", "1u", "1u", "4u", "4u", "1e-6f", "f32"), 0, 10),
)


def call(case: MetalCase, *, replace_index: int | None = None, replacement: str | None = None) -> str:
    args = list(case.args)
    if replace_index is not None:
        assert replacement is not None
        args[replace_index] = replacement
    joined = ",\n        ".join(args)
    return f"{case.name}(\n        {joined})"


def main() -> None:
    print("/* Generated by tests/generate_metal_guard_tests.py. Do not edit directly. */")
    print()
    print("static void test_generated_metal_guard_tests(void) {")
    print("    unsigned char mapping_storage[1] = {0u};")
    print("    void *mapping = mapping_storage;")
    print("    const size_t mapping_len = sizeof(mapping_storage);")
    print("    const uint32_t q4_type = 2u;")
    print("    const uint32_t q8_type = 8u;")
    print("    const uint32_t bad_type = 0u;")
    print("    uint32_t index = 0u;")
    print("    uint64_t offsets[1] = {0u};")
    print("    float f32[256];")
    print("    float f32_alt[256];")
    print("    float f32_third[256];")
    print("    for (size_t i = 0u; i < 256u; ++i) {")
    print("        f32[i] = 1.0f;")
    print("        f32_alt[i] = 0.5f;")
    print("        f32_third[i] = -0.25f;")
    print("    }")
    print()
    for case in CASES:
        label = case.name.replace("te_metal_", "metal ")
        invalid = call(case, replace_index=case.invalid_arg, replacement="NULL")
        unsupported = call(case, replace_index=case.unsupported_arg, replacement=case.unsupported_value)
        print("    {")
        print(f"        const te_status status = {invalid};")
        print(f'        expect_status_one_of(status, TE_STATUS_INVALID_ARGUMENT, TE_STATUS_UNSUPPORTED, "{label} invalid guard");')
        print("    }")
        print("    {")
        print(f"        const te_status status = {unsupported};")
        print(f'        expect_status_one_of(status, TE_STATUS_UNSUPPORTED, TE_STATUS_UNSUPPORTED, "{label} unsupported guard");')
        print("    }")
        print()
    print("}")


if __name__ == "__main__":
    main()
